# Generated by Django 2.0 on 2020-07-20 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('post_date', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateField(auto_now_add=True)),
                ('banner', models.ImageField(upload_to='')),
                ('is_large', models.BooleanField()),
                ('color', models.CharField(choices=[(0, 'Draft'), (1, 'Publish')], max_length=10)),
                ('min_read', models.CharField(max_length=10)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'db_table': 'post',
                'ordering': ['-post_date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Tag'),
        ),
    ]
