# Generated by Django 2.0 on 2020-07-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='status',
            field=models.CharField(choices=[(0, 'Draft'), (1, 'Publish')], default=None, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='color',
            field=models.CharField(choices=[(0, 'red'), (1, 'blue'), (2, 'green'), (3, 'orange'), (4, 'violet')], max_length=10),
        ),
    ]
