# Generated by Django 2.1.5 on 2020-07-20 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='color',
            field=models.CharField(choices=[(0, 'red'), (1, 'blue'), (2, 'green'), (3, 'orange'), (4, 'violet'), (5, 'empty')], max_length=10),
        ),
    ]
