# Generated by Django 2.1.5 on 2020-07-25 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200725_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='banner',
            field=models.TextField(blank=True, null=True),
        ),
    ]
