# Generated by Django 2.1.5 on 2020-07-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200725_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
